---
name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - templates/**
      - Chart.yaml
      - values.schema.json
      - values.yaml
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Lint and test the project
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Cache tools
        uses: actions/cache@v4
        with:
          path: ./bin
          key: ${{ runner.os }}-bin-${{ hashFiles('Makefile') }}

      - name: Install helm
        run: make $PWD/bin/helm

      - name: Lint chart
        run: ./bin/helm lint .

      - name: Test templates
        run: ./bin/helm template . > /dev/null
